server:
  port: 8089
  compression:
    enabled: true
    min-response-size: 20480
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript
spring:
#数据库连接池配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://39.105.100.109:5432/driver_exame
    username: postgres
    password: 123
#    前端模板配置
  thymeleaf:
    cache: false
    encoding: utf-8
  mvc:
    static-path-pattern: /static/**


#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#      naming:
#        strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.path: classpath:logback.xml
mapper:
  mappers: com.sjqp.driverexame.mapper.BaseMapper
  not-empty: false
  identity: postgresql
mybatis:
  type-aliases-package: com.sjqp.driverexame.entity
  configuration:
    map-underscore-to-camel-case: true
#mybatis-plus:
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    typeAliasesPackage: com.sjqp.driverexameentity
#    db-column-underline: true
pagehelper:
        helperDialect: postgresql
        reasonable: true
        supportMethodsArguments: true
        params: count=countSql



